name: CI/CD to Docker Hub

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  # CHANGE THIS to your Docker Hub username and image name
  # Format: username/repository-name
  IMAGE_NAME: your-dockerhub-username/github-api

jobs:
  # JOB 1: CHECK PHP CODE QUALITY
  php-quality:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: curl

      - name: Validate Composer
        run: composer validate --strict

      - name: Check PHP Syntax (Lint)
        run: find . -name "*.php" -print0 | xargs -0 -n1 php -l

  # JOB 2: BUILD AND PUSH TO DOCKER HUB
  docker-build:
    needs: php-quality
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          # Using the secrets you added in Step 1
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.IMAGE_NAME }}
          tags: |
            type=raw,value=latest,enable=${{ github.ref == 'refs/heads/main' }}
            type=sha

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          # Push only if it's NOT a Pull Request
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
